version: '3'

volumes:
  postgres_data: {}

services:
  postgres:
    build: ./compose/postgres/
    ports:
      - "5432:5432"
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.postgres
    command: postgres -c 'statement_timeout=20000'
