# Generated by Django 4.2.1 on 2023-06-16 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_positions_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('costs', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Информация о заказе',
                'verbose_name_plural': 'Информация о заказе',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Порядковый номер')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма заказа')),
                ('create_order', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказ',
            },
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='position',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='Заказ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='cart.orders'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='Позиция',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.positions'),
        ),
    ]
