# Generated by Django 4.2.1 on 2023-06-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderitem_orders_remove_cartitem_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_num',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Номер заказа'),
        ),
    ]
