# Generated by Django 4.2.1 on 2023-06-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_orders_order_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='Заказ',
        ),
        migrations.AddField(
            model_name='orders',
            name='item',
            field=models.ManyToManyField(to='cart.orderitem'),
        ),
    ]
