# Generated by Django 4.2.1 on 2023-06-18 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_positions_image'),
        ('cart', '0004_remove_orderitem_заказ_orders_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_num',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderPosition',
        ),
        migrations.CreateModel(
            name='PositionInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.orderposition', verbose_name='Товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.orders', verbose_name='Заказ')),
            ],
        ),
    ]
