# Generated by Django 4.2.1 on 2023-06-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_orders_item_remove_orders_order_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderposition',
            name='costs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, verbose_name='Сумма'),
        ),
    ]
