# Generated by Django 4.2.1 on 2023-06-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_orderposition_costs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderposition',
            old_name='costs',
            new_name='cost',
        ),
    ]
