# Generated by Django 4.2.1 on 2023-06-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_rename_costs_orderposition_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positioninorder',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товар в заказе'},
        ),
    ]
