# Generated by Django 4.2.1 on 2023-06-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_positioninorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('not_confirmed', 'Not confirmed'), ('confirmed', 'Confirmed'), ('in progress', 'An order is in progress'), ('completed', 'An order is completed')], default='not_confirmed', max_length=20, verbose_name='Order status'),
        ),
    ]
