# Generated by Django 4.2.1 on 2023-06-18 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_positions_image'),
        ('cart', '0009_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderposition',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='Позиция',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_positions', to='menu.positions'),
        ),
        migrations.AlterField(
            model_name='positioninorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions_in_orders', to='cart.orders', verbose_name='Заказ'),
        ),
    ]
