# Generated by Django 4.2.1 on 2023-06-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_remove_orderposition_cost_remove_orders_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderposition',
            old_name='Позиция',
            new_name='position',
        ),
    ]
