# Generated by Django 4.2.1 on 2023-06-15 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=40, verbose_name='ФИО')),
                ('mobile_number', models.CharField(help_text='+7**********', max_length=12, verbose_name='Номер телефона')),
                ('booking_comment', models.TextField(help_text='Столик: *, Количество гостей: *', max_length=255, verbose_name='Комментарий')),
                ('date_booking', models.DateTimeField(verbose_name='Дата и время брони')),
                ('date_reg', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время регистрации брони')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
            },
        ),
    ]
