# Generated by Django 4.2.1 on 2023-06-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=30, verbose_name='Название позиции')),
                ('position_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Цена позиции')),
                ('image', models.ImageField(default='images_positions/default.jpg', null=True, upload_to='images_positions/', verbose_name='Изображение позиции')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
    ]
