# Generated by Django 4.2.1 on 2023-06-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='image',
            field=models.ImageField(blank=True, default='images_positions/default.jpg', null=True, upload_to='images_positions/', verbose_name='Изображение позиции'),
        ),
    ]
