# Generated by Django 4.2.1 on 2023-06-15 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=40, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=30, verbose_name='Электронная почта')),
                ('feedback_comment', models.TextField(max_length=255, verbose_name='Комментарий')),
                ('date_record', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отзыва')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
